### ISSUE TITLE
Metal and Tensor::print()

### ISSUE THREAD

**Issue by oersted** [ssoudan/tch-m1#1]
`Tensor::print()` doesn't seem to segfault any more on PyTorch 1.12.1 and tch 0.8.0.

I did try Metal acceleration by applying your installation method with PyTorch nightly. At present it doesn't work mainly because `tch` is only compatible up to 1.12, but it sounds like we will get the Metal accelerated version working very soon: https://github.com/LaurentMazare/tch-rs/issues/542

PS: Thank you very much for publishing this, it's by far the cleanest method I've found.

**Comment by ssoudan** [comment]
Glad you found it useful.

The symlink is how I'm managed to get the repo layout to work for both OSX and linux - just get it point to the appropriate place on both architectures. The env variable in the cargo/config.toml are not conditional on the architecture AFAIK. 

Note that the generated binaries will also need the DYLD_LIBRARY_PATH (or LD_LIBRARY_PATH on linux) to work. Not found an equivalent of `gcc -L/somewhere/xxx` for cargo/rustc. If you launch the executable with `cargo run`, the env will be set. There must some option to pass to the linker to change the search paths.

**Comment by oersted** [comment]
Yep, I actually came up with the exact same method since I was working on Linux too. But I see what you mean, good point, I hadn't considered that the binaries need the env vars too. Nevertheless, I've never had a good reason not to use `cargo run`.

**Comment by oersted** [comment]
In any case, I wrote the issue to make you aware of these developments mostly so that the README can be updated.

**Comment by ssoudan** [comment]
Finally updated the example to PyTorch 1.13. Tensor transfers to and from MPS with to_device() works. Print() works for CPU tensors but not for MPS tensors as it seems to assume they are based on doubles - while they seems to be backed by floats (more digging needed).
